baseURL = "https://without-limits.thatteidlikaalsoup.team/"
languageCode = "en-us"
title = "College Women’s Ultimate Resources Manuals (in HTML)"
theme = "mediumish-gohugo-theme"

[params]
  mailchimp = "https://team.us12.list-manage.com/subscribe/post?u=6924dc1ec08c42f12738d464c&amp;id=302d7832cf"
  mailprotect = "b_6924dc1ec08c42f12738d464c_302d7832cf"

[params.index]
  picture = "/images/cover.jpg"
  title = "College Women’s Ultimate Resources Manuals"
  subtitle = "HTML versions of the articles in the Without Limits Ultimate Manuals"
  mdtext = '''This website is an attempt to make it easier to link to specific articles, and to make it easier to read on mobile devices.
  The original resources are available [here](http://withoutlimitsultimate.com/resources/)
  '''
  alertbar = true